### ISSUE TITLE
Missing step from instructions?

### ISSUE THREAD

**Issue by barulicm** [RoboJackets/eagle-libraries#7]
In Eagle 9.6.0, in order to actually access the libraries from a schematic, I had to first mark them as "used" in the control panel. Is this a normal step? If so, the README instructions should be updated to include it.

missing step:

- Expand the 'Libraries' group in the Control Panel. Locate the 'libraries' group within and expand it. In this group, you should now see a list of libraries with the 'RoboJackets' prefix. Right click the group name (libraries), and select "Use All". Each RoboJackets library should now have a green dot next to it.

**Comment by Arvind-Srinivasan** [comment]
Easy fix, I can do it.
